# Run this after installing docker desktop to create
# a local postgres database and pgadmin for managing it

services:
  db:
    image: postgres
    restart: always
    environment:
      # User will be postgres by default
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Mount the datasets directory to the container for bulk loading to Postgres
      # Make sure to change the path to your local datasets directory
      # ":/mnt/datasets" is telling the container to mount the datasets directory
      # to /mnt/datasets in the container
      - /home/tokyo/Etsy-SQL-Data-Warehouse/datasets/:/mnt/datasets

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    volumes:
      - pgadmindata:/var/lib/pgadmin
 
volumes:
  pgdata:
  pgadmindata: